[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
