[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
  'npm install',
  'cd server && npm install',
  'cd client && npm install'
]

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'cd server && npm start'
